version: '3.9'
name: NG.CASH-WALLET
services:
  frontend:
    container_name: NG.CASH-frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app/frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: NG.CASH-backend
    build: ./backend
    ports:
      - 8000:8000
    platform: linux/x86_64
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env/
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8000"]
      timeout: 10s
      retries: 5
    networks:
      - postgres
  db:
    image: postgres:14.1-alpine
    container_name: NG.CASH-db
    platform: linux/x86_64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: 'always'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 10s
      retries: 5
    networks:
      - postgres
    cap_add:
      - SYS_NICE

  pgadmin:
    container_name: NG.CASH-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin1234"
    volumes:
     - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

volumes:
 db-data:
 pgadmin-data:
networks:
  postgres:
    driver: bridge
